'use client';

import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { useState } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [expandedMenu, setExpandedMenu] = useState(null);

  const toggleMenu = (menuName) => {
    setExpandedMenu(expandedMenu === menuName ? null : menuName);
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "240px 1fr",
            gridTemplateRows: "64px 1fr",
            minHeight: "100vh",
          }}
        >
          <header
            style={{
              gridColumn: "1 / -1",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "0 1rem",
              borderBottom: "1px solid rgba(0,0,0,0.08)",
              color: "white",
              background: "#2D3247",
            }}
          >
            <div style={{ fontWeight: 700 }}>API Testing</div>
            <nav style={{ display: "flex", gap: "1rem" }}>
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/docs">Docs</Link>
            </nav>
          </header>

          <aside
            style={{
              padding: "1rem",
              borderRight: "1px solid rgba(0,0,0,0.06)",
              background: "#2F3349",
            }}
          >
            <nav
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "0.5rem",
                color: "white",
              }}
            >
              <Link href="/">Payment Module</Link>

              <div>
                <button
                  onClick={() => toggleMenu("payment-module")}
                  style={{
                    background: "none",
                    border: "none",
                    color: "inherit",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                    padding: "0.5rem",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  Payment Module
                  <span>{expandedMenu === "payment-module" ? "▼" : "▶"}</span>
                </button>
                {expandedMenu === "payment-module" && (
                  <div style={{ paddingLeft: "1rem", display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                    <Link href="/payment-module/add-customer" className="mb-2 border-b-black shadow-2xl">Add Customer</Link>
                    <Link href="/payment-module/direct-sale" className="mb-2 border-b-black shadow-2xl">Direct Sale With Card</Link>
                    <Link href="/payment-module/saved-card-sale" className="mb-2 border-b-black shadow-2xl">Sale With Saved Cards</Link>
                    <Link href="/payment-module/refund" className="mb-2 border-b-black shadow-2xl">Refund a transaction</Link>
                    <Link href="/payment-module/reverse" className="mb-2 border-b-black shadow-2xl">Reverse a transaction</Link>
                    <Link href="/payment-module/transaction-details" className="mb-2 border-b-black shadow-2xl">Get Transaction Details</Link>
                  </div>
                )}
              </div>

              <div>
                <button
                  onClick={() => toggleMenu("runs")}
                  style={{
                    background: "none",
                    border: "none",
                    color: "inherit",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                    padding: "0.5rem",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  Runs
                  <span>{expandedMenu === "runs" ? "▼" : "▶"}</span>
                </button>
                {expandedMenu === "runs" && (
                  <div style={{ paddingLeft: "1rem", display: "flex", flexDirection: "column", gap: "0.25rem" }}>
                    <Link href="/runs/active">Active Runs</Link>
                    <Link href="/runs/history">History</Link>
                  </div>
                )}
              </div>

              <Link href="/settings">Settings</Link>
            </nav>
          </aside>

          <main style={{ padding: "1.25rem" }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
